#!/usr/bin/env python3
"""Scaffold stub .sysml files and report migration status from
mapping/document_map.csv.

Usage:
    python3 tools/scaffold_stubs.py --report
    python3 tools/scaffold_stubs.py --stubs      # create missing stub files

A stub is only created for rows whose status is 'planned' AND whose
target_file does not yet exist. Rows pointing at existing files are
enrichment targets and are left alone. Standard library only — no deps.
"""
import argparse
import csv
import pathlib
import sys
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "mapping" / "document_map.csv"

STUB_TEMPLATE = """package {package} {{
    doc /* MIGRATION STUB — generated by tools/scaffold_stubs.py.
         * Source document: {source} ({revision}).
         * Wave {wave}. Populate per docs/MIGRATION_PLAN.md, then update
         * mapping/document_map.csv status for this row.
         * TODO Wave {wave}. */
}}
"""

def load_rows():
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def report(rows):
    by_status = Counter(r["status"] for r in rows)
    by_wave = Counter(r["wave"] for r in rows if r["status"] not in
                      ("reference_only", "out_of_scope", "superseded"))
    print("Migration status:")
    for k, v in sorted(by_status.items()):
        print(f"  {k:16s} {v}")
    print("Active rows by wave:")
    for k, v in sorted(by_wave.items()):
        print(f"  wave {k:2s}         {v}")

def make_stubs(rows):
    created = 0
    for r in rows:
        if r["status"] != "planned" or not r["target_file"]:
            continue
        target = ROOT / r["target_file"]
        if target.exists():
            continue
        package = r["target_package"].split(";")[0].strip()
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(STUB_TEMPLATE.format(
            package=package, source=r["source_document"],
            revision=r["revision"], wave=r["wave"]))
        print(f"created {target.relative_to(ROOT)}")
        created += 1
    if created == 0:
        print("No stubs to create (all planned targets exist).")
    else:
        print(f"{created} stub(s) created — run tools/validate.sh next.")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--stubs", action="store_true")
    args = ap.parse_args()
    rows = load_rows()
    if args.report or not args.stubs:
        report(rows)
    if args.stubs:
        make_stubs(rows)
    return 0

if __name__ == "__main__":
    sys.exit(main())
