function varargout = bar(varargin)
%%bar  No-op graphics shim returning a settable handle array (headless Octave).
  h = struct('FaceColor', {[],[],[],[],[],[],[],[],[],[]}, ...
             'EdgeColor', [], 'LineWidth', [], 'Color', [], ...
             'DisplayName', [], 'BarWidth', [], 'LineStyle', [], ...
             'Marker', [], 'CData', []);
  if nargout > 0, varargout = repmat({h}, 1, nargout); end
end
